// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA1p3F7zuvUW-zC5rvs0t2VJCXqUVEXeQ',
    appId: '1:995961724348:web:ec0810f1e6a6c22fdb5fb9',
    messagingSenderId: '995961724348',
    projectId: 'fir-easy-3ff86',
    authDomain: 'fir-easy-3ff86.firebaseapp.com',
    storageBucket: 'fir-easy-3ff86.firebasestorage.app',
    measurementId: 'G-Z5M8XSRY3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBZbwDtpIXSfOMxbJ4wv9gWh0-lsTECvg',
    appId: '1:995961724348:android:4156379e74eae40edb5fb9',
    messagingSenderId: '995961724348',
    projectId: 'fir-easy-3ff86',
    storageBucket: 'fir-easy-3ff86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ZILdxO9FSsmJMdCm793QYo4F4Jlt-eY',
    appId: '1:995961724348:ios:17d919db7cff8f41db5fb9',
    messagingSenderId: '995961724348',
    projectId: 'fir-easy-3ff86',
    storageBucket: 'fir-easy-3ff86.firebasestorage.app',
    iosBundleId: 'com.example.flutterPractice1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-ZILdxO9FSsmJMdCm793QYo4F4Jlt-eY',
    appId: '1:995961724348:ios:17d919db7cff8f41db5fb9',
    messagingSenderId: '995961724348',
    projectId: 'fir-easy-3ff86',
    storageBucket: 'fir-easy-3ff86.firebasestorage.app',
    iosBundleId: 'com.example.flutterPractice1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA1p3F7zuvUW-zC5rvs0t2VJCXqUVEXeQ',
    appId: '1:995961724348:web:9883de6c938560f3db5fb9',
    messagingSenderId: '995961724348',
    projectId: 'fir-easy-3ff86',
    authDomain: 'fir-easy-3ff86.firebaseapp.com',
    storageBucket: 'fir-easy-3ff86.firebasestorage.app',
    measurementId: 'G-SW1TD7BV09',
  );
}
